FROM alpine:latest

RUN apk update && apk add --no-cache curl unzip

RUN curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -o ngrok.zip \
    && unzip ngrok.zip \
    && mv ngrok /usr/local/bin/ngrok \
    && chmod +x /usr/local/bin/ngrok \
    && rm ngrok.zip

COPY entrypointngrok.sh .
RUN chmod +x entrypointngrok.sh

ENTRYPOINT [ "./entrypointngrok.sh" ]